<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-PQ2L7EM" failures="1" tests="1" name="Default test(failed)" time="0.096" errors="0" timestamp="2025-02-28T17:46:50 IST">
  <testcase classname="TestNGPractice.RetryAnalyzerExample" name="test1" time="0.024">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at TestNGPractice.RetryAnalyzerExample.test1(RetryAnalyzerExample.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="TestNGPractice.RetryAnalyzerExample" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed) -->
